# Generated by Django 4.1.3 on 2024-03-09 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greggor_productivity_companion', '0003_alter_category_name_alter_task_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
