# Generated by Django 4.2.7 on 2024-03-09 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greggor_productivity_companion', '0004_alter_user_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=520),
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('user', 'name', 'category')},
        ),
    ]
