# Generated by Django 4.2.7 on 2024-03-09 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greggor_productivity_companion', '0006_task_pointsuptodate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='pointsUpToDate',
            new_name='pointsForCurrentCycle',
        ),
    ]
