# Generated by Django 4.2.7 on 2024-03-09 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greggor_productivity_companion', '0007_rename_pointsuptodate_task_pointsforcurrentcycle'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workperiod',
            unique_together={('date', 'task', 'start_time', 'end_time')},
        ),
    ]
