# Generated by Django 4.2.7 on 2024-03-09 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greggor_productivity_companion', '0008_alter_workperiod_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workperiod',
            name='date',
            field=models.DateField(),
        ),
    ]
