# Generated by Django 4.2.7 on 2024-03-09 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greggor_productivity_companion', '0010_remove_task_pointsforcurrentcycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='bonus_points',
            field=models.IntegerField(default=0),
        ),
    ]
