# Generated by Django 4.1.3 on 2024-03-09 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greggor_productivity_companion', '0012_remove_user_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='actual_work_time',
        ),
    ]
