# Generated by Django 4.2.7 on 2024-03-10 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greggor_productivity_companion', '0014_user_profile_icon'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='task',
            unique_together=set(),
        ),
    ]
